// Fixes path alias not working in code generated by "tsc"
import customModuleLoader = require('module')
import path = require('path')

class CustomModuleLoader {
	public cOptions: any = require('../../tsconfig.json').compilerOptions

	public replacePaths: any = {}

	public constructor() {
		Object.keys(this.cOptions.paths).forEach(alias => {
			this.replacePaths[alias.replace(/\*.?/, '(.*)')] = this.cOptions.paths[
				alias
			][0].replace(/\*.?/, '$1')
		})
		//@ts-ignore
		customModuleLoader._originalResolveFilename = (customModuleLoader as any)._resolveFilename
		//@ts-ignore
		customModuleLoader._resolveFilename = (
			request: string,
			parent: customModuleLoader,
			isMain: boolean
		) => {
			Object.keys(this.replacePaths).forEach(matchString => {
				const regex = new RegExp(matchString)
				if (request.match(regex)) {
					const mapped = this.replacePaths[matchString]
					// Are we being mapped to something in node_modules?
					if (mapped.search('node_modules') > -1) {
						request = path.join(
							__dirname,
							'..',
							'..',
							request.replace(regex, mapped)
						)
					} else {
						request = path.join(
							__dirname,
							'..',
							'..',
							this.cOptions.outDir,
							request.replace(regex, mapped)
						)
					}
				}
			})

			// @ts-ignore
			return customModuleLoader._originalResolveFilename(
				request,
				parent,
				isMain
			)
		}
	}
}

new CustomModuleLoader()
